import {StyleSheet} from 'react-native';
import {
  borderRadius,
  colors,
  fontFamily,
  fontSize,
  marginHorizontal,
  responsiveHeight,
  responsiveWidth,
  spaceVertical,
} from '../../../styles/variables';

const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: colors.charcol},
  locationContainer: {flexDirection: 'row', alignItems: 'center'},
  header: {
    backgroundColor: colors.headerbgColor,
    flexDirection: 'row',
    height: responsiveHeight(7),
    alignItems: 'center',
  },

  searchicon: {
    height: responsiveHeight(2.5),
    width: responsiveWidth(5),
    marginLeft: marginHorizontal.XXS,
    tintColor: colors.gray10,
  },
  categoryname: {
    marginTop: spaceVertical.extraSmall,
    fontFamily: fontFamily.semiBold,
    color: 'black',
    alignSelf: 'center',
  },
  categoryimage: {
    height: responsiveWidth(23),
    width: responsiveWidth(23),
    alignSelf: 'center',
  },
  categoriesview: {
    height: responsiveHeight(18),
    width: responsiveWidth(32),
    borderWidth: 1,
    borderColor: colors.white,
    justifyContent: 'center',
    backgroundColor: 'white',
    borderRadius: borderRadius.semiLarge,
    shadowOpacity: 2,
    marginTop: spaceVertical.extraSmall,
    elevation: 5,
    marginVertical: spaceVertical.extraSmall,
  },
  topratedview: {
    height: responsiveHeight(21),
    width: responsiveWidth(32),
    borderWidth: 1,
    borderColor: colors.white,
    backgroundColor: colors.white,
    borderRadius: borderRadius.semiLarge,
    shadowOpacity: 2,
    marginTop: spaceVertical.extraSmall,
    elevation: 5,
    marginVertical: spaceVertical.extraSmall,
  },
  topratedname: {
    marginTop: spaceVertical.tiny,
    fontFamily: fontFamily.medium,
    fontSize: fontSize.semiSmall,
    color: colors.charcol,
    marginHorizontal: responsiveWidth(2),
    // textAlign:'center',
  },
  topratedimage: {
    height: responsiveHeight(11),
    width: responsiveWidth(32),
    borderRadius: borderRadius.otpradius,
    alignSelf: 'center',
  },
  swiper: {
    height: responsiveHeight(20),
    width: responsiveWidth(88),
    borderRadius: borderRadius.semiLarge,
    alignSelf: 'center',
    marginTop: spaceVertical.small,
  },
  verticleLine: {
    height: '50%',
    width: 1,
    backgroundColor: colors.nocolor,
  },
  headername: {
    fontSize: fontSize.sizeGuideTxt,
    fontFamily: fontFamily.bold,
    color: colors.charcol,
    marginLeft: marginHorizontal.semiSmall,
    marginTop: spaceVertical.small,
  },
  searchbarview: {
    flexDirection: 'row',
    backgroundColor: colors.white,
    width: responsiveWidth(92),
    height: responsiveHeight(6),
    paddingStart: 10,
    borderColor: '#000000',
    alignSelf: 'center',
    alignItems: 'center',
    borderRadius: borderRadius.normal,
    bottom: 18,
    elevation: 5,
  },
  body: {
    flex: 1,
    marginTop: spaceVertical.normal,
    backgroundColor: colors.white,
    borderTopStartRadius: 22,
    borderTopEndRadius: 22,
  },
  body_dark: {
    flex: 1,
    marginTop: spaceVertical.normal,
    backgroundColor: colors.black,
    borderTopStartRadius: 22,
    borderTopEndRadius: 22,
  },
  logotext: {
    height: responsiveHeight(5),
    width: responsiveWidth(18),
    alignSelf: 'center',
    marginLeft: marginHorizontal.small,
  },
  headerRightIcons: {
    position: 'absolute',
    right: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  icbell: {
    height: responsiveWidth(6),
    width: responsiveWidth(6),
  },
  profileicon: {
    height: responsiveWidth(7),
    width: responsiveWidth(7),
    marginLeft: responsiveWidth(3),
  },
  iclocation: {
    height: responsiveHeight(4),
    width: responsiveWidth(8),
  },
  locationview: {
    marginLeft: responsiveWidth(5),
    flexDirection: 'row',
    marginTop: spaceVertical.extraSmall,
    alignItems: 'center',
    width: responsiveWidth(90),
    justifyContent: 'space-between',
  },
  locationTitle: {
    marginLeft: marginHorizontal.extraSmall,
    width: responsiveWidth(20),
  },
  locationtext: {
    color: colors.HARD_WHITE,
    fontFamily: fontFamily.regular,
    width: responsiveWidth(88),
  },
  locationtext1: {
    fontSize: fontSize.normal,
    color: colors.HARD_WHITE,
    fontFamily: fontFamily.regular,
    width: responsiveWidth(88),
  },
  appLogo: {
    width: responsiveWidth(27),
    height: responsiveHeight(5),
  },
  input: {
    height: responsiveHeight(7),
    width: responsiveWidth(80),
    fontFamily: fontFamily.regular,
    borderRadius: borderRadius.semiLarge,
    top: 3,
    paddingStart: 10,
  },
  loc_color: {
    color: colors.locationtext,
  },
  white_col: {
    color: colors.white,
  },
  gray_color: {
    color: colors.darkGray,
  },
});

export {styles};
